Repository tomriddle77/hactober2021, pull requests merged in 2021-10, with the labels that each got.

#10 Create Maximum profit by buying and selling a share atmost twice.cpp
  Public/Maximum profit by buying and selling a share atmost twice.cpp
Labels: enhancement

#14 Create To check if two numbers are equal without using arithmetic ope…
  Public/To check if two numbers are equal without using arithmetic operators or comparison operators.
Labels: enhancement

#15 Create Maximize count of indices with same element by pairing rows fr…
  Public/Maximize count of indices with same element by pairing rows from given Matrices.
Labels: enhancement

#17 Create OpenCV C++ Program for Face Detection.
  Public/OpenCV C++ Program for Face Detection.
Labels: enhancement

#20 Create print Postorder traversal from Preorder and Inorder traversal …
  Public/print Postorder traversal from Preorder and Inorder traversal of a tree using C++ program?
Labels: c++

#13 Update game_with_human.cpp
  Public/game_with_human.cpp
Labels: documentation

#22 Create longest palindrome.cpp
  Public/HP.cpp
Labels: enhancement, c++

#23 Create Longest Common Prefix.cpp
  Public/Longest Common Prefix.cpp
Labels: enhancement, c++

#18 Create_Maximum_Product_Subarray.cpp
  Public/Maximum_Product_Subarray_Leetcode_Medium.cpp
Labels: enhancement

#26 Create High-low game in c++.
  High-low game in c++.
Labels: enhancement, hactoberfest-accepted

#16 Create To create a simple tic-tac-toe game with an AI as a C++ consol…
  To create a simple tic-tac-toe game with an AI as a C++ console application.
Labels: enhancement, hactoberfest-accepted

#27 Create C++ Program to print a man using graphics.
  C++ Program to print a man using graphics.
Labels: c++, hactoberfest-accepted
